#!/usr/bin/env python
from selenium import webdriver
import time
browser = webdriver.Chrome()
browser.get("https://www.google.com")
input = browser.find_element_by_id('lst-ib')
input.send_keys('selenium')
time.sleep(3)
button = browser.find_element_by_id('_fZl')
button.submit()
time.sleep(3)
browser.quit()
